apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres

          image: postgres:17

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_USER
              value: taskuser

            - name: POSTGRES_PASSWORD
              value: taskpassword

            - name: POSTGRES_DB
              value: taskdb

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage

      volumes:
        - name: postgres-storage

          persistentVolumeClaim:
            claimName: postgres-pvc